### ISSUE TITLE
Impression

### ISSUE THREAD

**Issue by smygarn** [Unity-Technologies/SmallOfficeRayTracing#6]
I expected a scene like this to be a good demonstration about how ray tracing in Unity is progressing. 

- After opening the project, you have to fix some issues with the HD Render Pipeline Wizard. Is this how it is supposed to work in Unity ? After this was fixed, it's still look aweful because it's just screen-space-reflection everywhere. You can even see the reflection from the sky through the concrete walls. If I turn off/on raytracing features in the ray tracing settings profile , nothing happens.

To create a good demonstration ray tracing scene it would have been perfect if there are only one light source that creates all the light, but this simple scene got six very advanced point lights and one Area light and a directional light. I would expect that ray tracing scenes didn't need tricky dirty / magic light sources?

I tried it in Unity 2018.3.b10 and 2020.1.0a9 and got some non critical errors in the console:
- Failed to create Convex Mesh from source mesh "Meeting_Room_Table_Round". Reached the maximum polygons limit (256). Consider simplifying your mesh.
- d3d12: generating mipmaps for array textures is not yet supported.

Well, it's really nice to see some progress but unfortunately, it seems that Epic Games with Unreal Engine is at least a year ahead in this area.

**Comment by michal-z-amd** [comment]
Hi, I've tried this with latest HDRP 8.x from Github and it works fine.

**Comment by sebastienlagarde** [comment]
Thanks for the feedback. We have updated the scene and provide different setup. Not what you are expecting but better than what was available.
